source: .
destination: ./_site
plugins: ./_plugins

exclude: imports/, Rakefile

auto: true
server: false
server_port: 4000

baseurl: http://lincolnmullen.com/jsrdev/
#baseurl: /
#url: http://jsr.fsu.edu
permalink: none

currentissue: vol13
